<?= $this->extend('layouts/app') ?>
<?= $this->section('title') ?>Alertas de stock<?= $this->endSection() ?>
<?= $this->section('main') ?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="h3 mb-1">Alertas de stock bajo</h1><p class="text-body-secondary mb-0">Materiales cuya existencia alcanzó o bajó del mínimo configurado.</p></div><a class="btn btn-outline-primary" href="<?= url_to('inventory-stocks') ?>">Ver existencias</a></div>
<?= $this->include('partials/flash') ?>
<form class="row g-2 mb-3" method="get"><div class="col-md-4"><label class="form-label" for="warehouse_id">Bodega</label><select class="form-select" id="warehouse_id" name="warehouse_id"><option value="">Todas las bodegas</option><?php foreach ($warehouses as $warehouse): ?><option value="<?= esc((string) $warehouse['id']) ?>" <?= $warehouseId === (int) $warehouse['id'] ? 'selected' : '' ?>><?= esc($warehouse['name']) ?></option><?php endforeach ?></select></div><div class="col-auto align-self-end"><button class="btn btn-outline-secondary">Filtrar</button></div></form>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Bodega</th><th>Código</th><th>Material</th><th class="text-end">Existencia</th><th class="text-end">Mínimo</th><th class="text-end">Déficit</th><th>Notificación</th></tr></thead><tbody>
<?php foreach ($records as $record): ?><?php $deficit = max(0, (float) $record['minimum_stock'] - (float) $record['quantity']); ?><tr><td><?= esc($record['warehouse_name']) ?></td><td class="font-monospace"><?= esc($record['code']) ?></td><td><?= esc($record['name']) ?></td><td class="text-end text-danger fw-semibold"><?= esc(number_format((float) $record['quantity'], 3, ',', '.')) ?> <?= esc($record['unit_symbol']) ?></td><td class="text-end"><?= esc(number_format((float) $record['minimum_stock'], 3, ',', '.')) ?></td><td class="text-end"><?= esc(number_format($deficit, 3, ',', '.')) ?></td><td><?= $record['last_notified_at'] ? esc($record['last_notified_at']) : '<span class="badge text-bg-secondary">Correo no enviado</span>' ?></td></tr><?php endforeach ?>
<?php if ($records === []): ?><tr><td class="text-center text-body-secondary py-4" colspan="7">No existen alertas activas para el filtro seleccionado.</td></tr><?php endif ?>
</tbody></table></div></div>
<p class="small text-body-secondary mt-3 mb-0">Las notificaciones por correo permanecen deshabilitadas. El sistema ya conserva el campo de última notificación para aplicar control de frecuencia cuando se habiliten.</p>
<?= $this->endSection() ?>
