<!doctype html><html lang="es"><head><meta charset="utf-8"><style>
@page{margin:24px 30px}body{font-family:DejaVu Sans,sans-serif;color:#182235;font-size:10px}.head{border-bottom:3px solid #155eef;padding-bottom:12px;margin-bottom:16px}.brand{font-size:20px;font-weight:bold;color:#0b3558}.guide{float:right;text-align:right}.guide strong{font-size:16px}.grid{width:100%;border-collapse:collapse;margin-bottom:14px}.grid td{width:50%;padding:4px 8px;vertical-align:top}.label{font-weight:bold;color:#52627a}.items{width:100%;border-collapse:collapse}.items th{background:#eaf1fb;text-align:left;padding:7px;border:1px solid #b9c8db}.items td{padding:7px;border:1px solid #cbd6e3}.num{text-align:right}.pending{color:#b54708;font-weight:bold}.signatures{margin-top:45px;width:100%}.signatures td{width:50%;text-align:center;padding:0 25px}.line{border-top:1px solid #26364d;padding-top:6px}.verify{margin-top:22px;padding:8px;background:#f3f6fa;font-size:8px;word-break:break-all}.footer{position:fixed;bottom:0;left:0;right:0;text-align:center;color:#6b778c;font-size:8px}
</style></head><body>
<div class="head"><div class="guide">Guía de remisión<br><strong><?= esc($dispatch['guide_number'] ?: $dispatch['movement_number']) ?></strong><br>Estado: <?= esc($status) ?></div><div class="brand">Inventario de materiales</div><div>Sistema institucional de control y trazabilidad</div></div>
<table class="grid"><tr><td><span class="label">Fecha de emisión:</span> <?= esc($dispatch['issue_date'] ?? date('Y-m-d')) ?><br><span class="label">Fecha de inicio:</span> <?= esc($dispatch['start_date'] ?? '—') ?><br><span class="label">Fecha de fin:</span> <?= esc($dispatch['end_date'] ?? '—') ?><br><span class="label">Bodega:</span> <?= esc($dispatch['warehouse_name']) ?><br><span class="label">Partida:</span> <?= esc($dispatch['origin_place'] ?? '—') ?></td><td><span class="label">Autorización:</span> <?= esc($dispatch['authorization_number'] ?? '—') ?><br><span class="label">Emisor:</span> <?= esc($dispatch['issuer_name'] ?? '—') ?><br><span class="label">RUC/C.I.:</span> <?= esc($dispatch['issuer_tax_identifier'] ?? '—') ?><br><span class="label">Documento relacionado:</span> <?= esc($dispatch['related_document_number'] ?? '—') ?></td></tr><tr><td><span class="label">Transportista:</span> <?= esc($dispatch['transporter_name'] ?? '—') ?><br><span class="label">RUC/C.I.:</span> <?= esc($dispatch['transporter_identifier'] ?? '—') ?><br><span class="label">Placa:</span> <?= esc($dispatch['vehicle_plate'] ?? '—') ?></td><td><span class="label">Destinatario:</span> <?= esc($dispatch['destination_name'] ?? '—') ?><br><span class="label">RUC/C.I.:</span> <?= esc($dispatch['destination_identifier'] ?? '—') ?><br><span class="label">Dirección:</span> <?= esc($dispatch['destination_address'] ?? '—') ?><br><span class="label">Ruta:</span> <?= esc($dispatch['route_description'] ?? '—') ?></td></tr></table>
<p><span class="label">Motivo:</span> <?= esc($dispatch['reason'] ?? '—') ?><br><span class="label">Descripción:</span> <?= esc($dispatch['description'] ?? '—') ?></p>
<table class="items"><thead><tr><th>Producto</th><th>Unidad</th><th class="num">Solicitado</th><th class="num">Entregado</th><th class="num">Pendiente</th></tr></thead><tbody><?php foreach($items as $item): ?><tr><td><?= esc($item['code'].' - '.$item['name']) ?></td><td><?= esc($item['unit_symbol']) ?></td><td class="num"><?= esc(number_format((float)$item['requested_quantity'],3,',','.')) ?></td><td class="num"><?= esc(number_format((float)$item['delivered_quantity'],3,',','.')) ?></td><td class="num pending"><?= esc(number_format((float)$item['pending_quantity'],3,',','.')) ?></td></tr><?php endforeach ?></tbody></table>
<table class="signatures"><tr><td><div class="line"><?= esc($dispatch['delivered_by_name']) ?><br>Entrega</div></td><td><div class="line"><?= esc($dispatch['received_by_name']) ?><br>Recibe · <?= esc($dispatch['received_by_area_name'] ?? '') ?></div></td></tr></table>
<div class="verify">Consulta verificable: <?= esc($verificationUrl) ?></div><div class="footer">Documento generado por el sistema institucional de inventario.</div></body></html>
