<?= $this->extend('layouts/app') ?>
<?= $this->section('title') ?>Requisiciones<?= $this->endSection() ?>
<?= $this->section('main') ?>
<div class="d-flex flex-wrap justify-content-between gap-3 align-items-center mb-4"><div><p class="app-eyebrow mb-1">Despachos</p><h1 class="h2 mb-1">Requisiciones de materiales</h1><p class="text-body-secondary mb-0">Aprobación y reserva previa a la emisión de una guía.</p></div><?php if (auth()->user()?->can('inventory.dispatch_requests.create')): ?><a class="btn btn-primary" href="<?= url_to('dispatch-requests-new') ?>">+ Nueva requisición</a><?php endif ?></div>
<?= $this->include('partials/flash') ?>
<div class="card app-table-card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Número</th><th>Fecha</th><th>Bodega</th><th>Destinatario</th><th>Solicitante</th><th>Estado</th><th class="text-end">Acciones</th></tr></thead><tbody>
<?php $labels=['PENDING'=>'Pendiente','APPROVED'=>'Aprobada','REJECTED'=>'Rechazada','CONVERTED'=>'Convertida en guía']; $colors=['PENDING'=>'warning','APPROVED'=>'success','REJECTED'=>'danger','CONVERTED'=>'primary']; foreach ($records as $record): ?><tr><td class="font-monospace"><?= esc($record['request_number']) ?></td><td><?= esc($record['requested_at']) ?></td><td><?= esc($record['warehouse_name']) ?></td><td><?= esc($record['recipient_name']) ?></td><td><?= esc($record['requested_by_name']) ?></td><td><span class="badge text-bg-<?= $colors[$record['status']] ?>"><?= $labels[$record['status']] ?></span></td><td><div class="d-flex flex-wrap justify-content-end gap-2"><a class="btn btn-sm btn-outline-primary" href="<?= url_to('dispatch-request-show',$record['id']) ?>">Ver detalle</a><?php if ($record['status']==='APPROVED' && auth()->user()?->can('inventory.exits.create')): ?><a class="btn btn-sm btn-primary" href="<?= url_to('inventory-exit-new') ?>?dispatch_request_id=<?= esc((string)$record['id']) ?>">Preparar guía</a><?php endif ?></div></td></tr><?php endforeach ?>
<?php if ($records===[]): ?><tr><td colspan="7" class="app-empty-state">No existen requisiciones.</td></tr><?php endif ?></tbody></table></div></div>
<?= $this->endSection() ?>
