<?= $this->extend('layouts/app') ?>
<?= $this->section('title') ?>Detalle de requisición<?= $this->endSection() ?>
<?= $this->section('main') ?>
<?php $labels=['PENDING'=>'Pendiente','APPROVED'=>'Aprobada','REJECTED'=>'Rechazada','CONVERTED'=>'Convertida en guía']; $colors=['PENDING'=>'warning','APPROVED'=>'success','REJECTED'=>'danger','CONVERTED'=>'primary']; ?>
<div class="d-flex flex-wrap justify-content-between gap-3 align-items-center mb-4"><div><p class="app-eyebrow mb-1">Requisición</p><h1 class="h2 mb-1"><?= esc($record['request_number']) ?></h1><span class="badge text-bg-<?= $colors[$record['status']] ?>"><?= $labels[$record['status']] ?></span></div><a class="btn btn-outline-secondary" href="<?= url_to('dispatch-requests') ?>">Volver</a></div>
<?= $this->include('partials/flash') ?>
<div class="row g-4"><div class="col-lg-8"><div class="card app-table-card"><div class="card-header"><strong>Materiales solicitados</strong></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Código</th><th>Material</th><th class="text-end">Cantidad</th><th>Unidad</th></tr></thead><tbody><?php foreach ($items as $item): ?><tr><td class="font-monospace"><?= esc($item['code']) ?></td><td><?= esc($item['material_name']) ?></td><td class="text-end"><?= esc(number_format((float)$item['quantity'],3,',','.')) ?></td><td><?= esc($item['unit_symbol']) ?></td></tr><?php endforeach ?></tbody></table></div></div></div>
<div class="col-lg-4"><div class="card"><div class="card-body"><h2 class="h5">Datos de entrega</h2><dl class="mb-0"><dt>Bodega</dt><dd><?= esc($record['warehouse_name']) ?></dd><dt>Destinatario</dt><dd><?= esc($record['recipient_name']) ?><br><small class="text-body-secondary"><?= esc($record['recipient_document'] ?: 'Sin identificación') ?></small></dd><dt>Dirección / ruta</dt><dd><?= esc($record['recipient_address'] ?: 'No registrada') ?><br><?= esc($record['recipient_route'] ?: '') ?></dd><dt>Solicitante</dt><dd><?= esc($record['requested_by_name']) ?></dd><dt>Motivo</dt><dd><?= nl2br(esc($record['reason'])) ?></dd><?php if (!empty($record['observations'])): ?><dt>Observaciones</dt><dd><?= nl2br(esc($record['observations'])) ?></dd><?php endif ?></dl></div></div>
<?php if ($record['status']==='PENDING' && auth()->user()?->can('inventory.dispatch_requests.approve')): ?><div class="card mt-3"><div class="card-body"><h2 class="h5">Decisión</h2><form method="post" action="<?= url_to('dispatch-request-decide',$record['id']) ?>"><?= csrf_field() ?><label class="form-label" for="comment">Comentario</label><textarea class="form-control mb-3" id="comment" name="comment" maxlength="2000" rows="3"></textarea><div class="d-flex gap-2"><button class="btn btn-success" name="decision" value="approve">Aprobar y reservar</button><button class="btn btn-outline-danger" name="decision" value="reject">Rechazar</button></div></form></div></div><?php endif ?>
<?php if ($record['status']==='APPROVED' && auth()->user()?->can('inventory.exits.create')): ?><a class="btn btn-primary w-100 mt-3" href="<?= url_to('inventory-exit-new') ?>?dispatch_request_id=<?= esc((string)$record['id']) ?>">Preparar guía de remisión</a><?php endif ?></div></div>
<?= $this->endSection() ?>
