<?= $this->extend('layouts/app') ?>
<?= $this->section('title') ?>Materiales<?= $this->endSection() ?>
<?= $this->section('main') ?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="h3 mb-1">Materiales</h1><p class="text-body-secondary mb-0">Catálogo y existencia total informativa.</p></div><?php if (auth()->user()?->can('materials.create')): ?><a class="btn btn-primary" href="<?= url_to('materials-new') ?>">Nuevo material</a><?php endif ?></div>
<?= $this->include('partials/flash') ?>
<form class="row g-2 mb-3" method="get"><div class="col-sm-6 col-lg-4"><input class="form-control" name="q" value="<?= esc($search) ?>" placeholder="Buscar por código o nombre"></div><div class="col-auto"><button class="btn btn-outline-secondary">Buscar</button></div></form>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Código</th><th>Material</th><th>Categoría</th><th>Unidad</th><th class="text-end">Existencia</th><th>Estado</th><th class="text-end">Acciones</th></tr></thead><tbody>
<?php foreach ($records as $record): ?><tr><td><?= esc($record['code']) ?></td><td><div class="fw-semibold"><?= esc($record['name']) ?></div><small class="text-body-secondary"><?= $record['allows_fraction'] ? 'Admite fracciones' : 'Solo cantidades enteras' ?></small></td><td><?= esc($record['category_name']) ?></td><td><?= esc($record['unit_name']) ?> (<?= esc($record['unit_symbol']) ?>)</td><td class="text-end"><?= esc(number_format((float) $record['current_stock'], 3, ',', '.')) ?><?php if ((int) $record['low_stock_warehouses'] > 0): ?><div><a class="badge text-bg-danger text-decoration-none" href="<?= url_to('inventory-alerts') ?>"><?= esc((string) $record['low_stock_warehouses']) ?> bodega(s) con stock bajo</a></div><?php endif ?></td><td><span class="badge text-bg-<?= $record['active'] ? 'success' : 'secondary' ?>"><?= $record['active'] ? 'Activo' : 'Inactivo' ?></span></td><td><div class="d-flex justify-content-end gap-2"><?php if (auth()->user()?->can('materials.update')): ?><a class="btn btn-sm btn-outline-primary" href="<?= url_to('materials-edit', $record['id']) ?>">Editar</a><?php endif ?><?php if (auth()->user()?->can('materials.deactivate')): ?><form method="post" action="<?= url_to('materials-toggle', $record['id']) ?>"><?= csrf_field() ?><button class="btn btn-sm btn-outline-<?= $record['active'] ? 'danger' : 'success' ?>" type="submit"><?= $record['active'] ? 'Desactivar' : 'Activar' ?></button></form><?php endif ?></div></td></tr><?php endforeach ?>
<?php if ($records === []): ?><tr><td class="text-center text-body-secondary py-4" colspan="7">No hay materiales registrados.</td></tr><?php endif ?>
</tbody></table></div></div><div class="mt-3"><?= $pager->links() ?></div>
<?= $this->endSection() ?>
