<?= $this->extend('layouts/app') ?>
<?= $this->section('title') ?>Proveedores<?= $this->endSection() ?>
<?= $this->section('main') ?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="h3 mb-1">Proveedores</h1><p class="text-body-secondary mb-0">Proveedores, donantes y contactos de entrada.</p></div><?php if (auth()->user()?->can('suppliers.create')): ?><a class="btn btn-primary" href="<?= url_to('suppliers-new') ?>">Nuevo proveedor</a><?php endif ?></div>
<?= $this->include('partials/flash') ?>
<form class="row g-2 mb-3" method="get"><div class="col-sm-6 col-lg-4"><input class="form-control" name="q" value="<?= esc($search) ?>" placeholder="Buscar nombre o documento"></div><div class="col-auto"><button class="btn btn-outline-secondary">Buscar</button></div></form>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Nombre</th><th>Documento</th><th>Contacto</th><th>Estado</th><th class="text-end">Acciones</th></tr></thead><tbody>
<?php foreach ($records as $record): ?><tr><td><?= esc($record['name']) ?></td><td><?= esc(trim(($record['document_type'] ?? '') . ' ' . ($record['document_number'] ?? '')) ?: '—') ?></td><td><?= esc($record['contact_name'] ?? $record['email'] ?? '—') ?></td><td><span class="badge text-bg-<?= $record['active'] ? 'success' : 'secondary' ?>"><?= $record['active'] ? 'Activo' : 'Inactivo' ?></span></td><td><div class="d-flex justify-content-end gap-2"><?php if (auth()->user()?->can('suppliers.update')): ?><a class="btn btn-sm btn-outline-primary" href="<?= url_to('suppliers-edit', $record['id']) ?>">Editar</a><?php endif ?><?php if (auth()->user()?->can('suppliers.deactivate')): ?><form method="post" action="<?= url_to('suppliers-toggle', $record['id']) ?>"><?= csrf_field() ?><button class="btn btn-sm btn-outline-<?= $record['active'] ? 'danger' : 'success' ?>" type="submit"><?= $record['active'] ? 'Desactivar' : 'Activar' ?></button></form><?php endif ?></div></td></tr><?php endforeach ?>
</tbody></table></div></div><div class="mt-3"><?= $pager->links() ?></div>
<?= $this->endSection() ?>
