<?= $this->extend('layouts/app') ?>
<?= $this->section('title') ?>Valoraciones<?= $this->endSection() ?>
<?= $this->section('main') ?>
<div class="mb-4"><h1 class="h3 mb-1">Valoración financiera</h1><p class="text-body-secondary mb-0">Completa costos mediante eventos nuevos; los movimientos originales permanecen intactos.</p></div>
<?= $this->include('partials/flash') ?>
<div class="alert alert-info">La parte de una entrada que todavía permanece físicamente en inventario actualiza el costo promedio. La parte ya consumida queda registrada separadamente para reportes financieros.</div>
<section class="mb-5"><h2 class="h5 mb-3">Pendientes de valoración</h2><div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Movimiento</th><th>Material</th><th>Bodega</th><th class="text-end">Pendiente</th><th>Motivo original</th><th>Completar</th></tr></thead><tbody>
<?php foreach ($pending as $record): ?><tr><td><a href="<?= url_to('inventory-movement-show', $record['movement_id']) ?>" class="font-monospace"><?= esc($record['movement_number']) ?></a><div class="small text-body-secondary"><?= esc($record['created_at']) ?></div></td><td><span class="font-monospace"><?= esc($record['material_code']) ?></span><br><?= esc($record['material_name']) ?></td><td><?= esc($record['warehouse_name']) ?></td><td class="text-end fw-semibold"><?= esc(number_format((float) $record['remaining_quantity'], 3, ',', '.')) ?> <?= esc($record['unit_symbol']) ?></td><td><?= esc($record['no_cost_reason'] ?? 'Sin detalle') ?></td><td><form method="post" action="<?= url_to('inventory-valuation-complete', $record['movement_item_id']) ?>" class="row g-2"><?= csrf_field() ?><div class="col-6"><input class="form-control form-control-sm" type="number" name="quantity" min="0.001" max="<?= esc((string) $record['remaining_quantity']) ?>" step="0.001" value="<?= esc((string) $record['remaining_quantity']) ?>" aria-label="Cantidad" required></div><div class="col-6"><input class="form-control form-control-sm" type="number" name="unit_cost" min="0.000001" step="0.000001" placeholder="Costo unitario" required></div><div class="col-8"><input class="form-control form-control-sm" name="reason" minlength="5" maxlength="1000" placeholder="Motivo o soporte" required></div><div class="col-4"><button class="btn btn-sm btn-primary w-100" type="submit">Registrar</button></div></form></td></tr><?php endforeach ?>
<?php if ($pending === []): ?><tr><td class="text-center text-body-secondary py-4" colspan="6">No existen entradas pendientes de valoración.</td></tr><?php endif ?>
</tbody></table></div></div></section>
<section><h2 class="h5 mb-3">Historial inmutable</h2><div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Evento</th><th>Movimiento</th><th>Material</th><th class="text-end">Cantidad base</th><th class="text-end">Costo</th><th class="text-end">Impacto inventario</th><th>Registrado por</th><th>Corrección</th></tr></thead><tbody>
<?php foreach ($history as $record): ?><tr><td><span class="font-monospace"><?= esc($record['valuation_number']) ?></span><div><span class="badge text-bg-<?= $record['event_type'] === 'ALLOCATION' ? 'success' : 'warning' ?>"><?= $record['event_type'] === 'ALLOCATION' ? 'Valoración' : 'Corrección' ?></span></div></td><td><a href="<?= url_to('inventory-movement-show', $record['movement_id']) ?>"><?= esc($record['movement_number']) ?></a></td><td><?= esc($record['material_code'] . ' - ' . $record['material_name']) ?><div class="small text-body-secondary"><?= esc($record['warehouse_name']) ?></div></td><td class="text-end"><?= esc(number_format((float) $record['quantity_basis'], 3, ',', '.')) ?></td><td class="text-end"><?= esc(number_format((float) $record['unit_cost'], 6, ',', '.')) ?><?php if ($record['event_type'] === 'ALLOCATION' && (float) $record['effective_unit_cost'] !== (float) $record['unit_cost']): ?><div class="small text-body-secondary">Vigente: <?= esc(number_format((float) $record['effective_unit_cost'], 6, ',', '.')) ?></div><?php endif ?></td><td class="text-end"><?= esc(number_format((float) $record['inventory_value_delta'], 2, ',', '.')) ?></td><td><?= esc($record['created_by_name']) ?><div class="small text-body-secondary"><?= esc($record['created_at']) ?></div></td><td><?php if ($record['event_type'] === 'ALLOCATION'): ?><form method="post" action="<?= url_to('inventory-valuation-correct', $record['id']) ?>" class="d-flex flex-column gap-2"><?= csrf_field() ?><input class="form-control form-control-sm" type="number" name="unit_cost" min="0.000001" step="0.000001" value="<?= esc((string) $record['effective_unit_cost']) ?>" aria-label="Nuevo costo" required><input class="form-control form-control-sm" name="reason" minlength="5" maxlength="1000" placeholder="Motivo de corrección" required><button class="btn btn-sm btn-outline-warning" type="submit">Corregir</button></form><?php else: ?>—<?php endif ?></td></tr><?php endforeach ?>
<?php if ($history === []): ?><tr><td class="text-center text-body-secondary py-4" colspan="8">Todavía no existen eventos de valoración.</td></tr><?php endif ?>
</tbody></table></div></div></section>
<?= $this->endSection() ?>
