<?= $this->extend('layouts/app') ?>
<?= $this->section('title') ?>Movimiento <?= esc($movement['movement_number']) ?><?= $this->endSection() ?>
<?= $this->section('main') ?>
<?= $this->include('partials/flash') ?>
<div class="d-flex justify-content-between align-items-start gap-3 mb-4"><div><h1 class="h3 mb-1">Movimiento <?= esc($movement['movement_number']) ?></h1><p class="text-body-secondary mb-0"><?= esc($movement['warehouse_name']) ?> · <?= esc($movement['created_at']) ?></p></div><a class="btn btn-outline-secondary" href="<?= url_to('inventory-movements') ?>">Volver</a></div>
<div class="row g-3 mb-4"><div class="col-lg-8"><div class="card border-0 shadow-sm h-100"><div class="card-body"><dl class="row mb-0"><dt class="col-sm-4">Tipo</dt><dd class="col-sm-8"><?= esc(['ENTRY'=>'Entrada','EXIT'=>'Salida','ADJUSTMENT'=>'Ajuste','REVERSAL'=>'Reversión'][$movement['type']] ?? $movement['type']) ?></dd><dt class="col-sm-4">Registrado por</dt><dd class="col-sm-8"><?= esc($movement['created_by_name']) ?></dd><dt class="col-sm-4">Entrega</dt><dd class="col-sm-8"><?= esc($movement['delivered_by_name']) ?></dd><dt class="col-sm-4">Recibe</dt><dd class="col-sm-8"><?= esc($movement['received_by_name']) ?></dd><?php if ($movement['received_by_area_name']): ?><dt class="col-sm-4">Área receptora</dt><dd class="col-sm-8"><?= esc($movement['received_by_area_name']) ?></dd><?php endif ?><?php if ($movement['supplier_name']): ?><dt class="col-sm-4">Proveedor</dt><dd class="col-sm-8"><?= esc($movement['supplier_name']) ?></dd><?php endif ?><?php if ($movement['document_number']): ?><dt class="col-sm-4">Documento</dt><dd class="col-sm-8"><?= esc($movement['document_number']) ?></dd><?php endif ?><?php if ($movement['reason']): ?><dt class="col-sm-4">Motivo</dt><dd class="col-sm-8"><?= esc($movement['reason']) ?></dd><?php endif ?><?php if ($movement['original_movement_id']): ?><dt class="col-sm-4">Movimiento original</dt><dd class="col-sm-8"><a href="<?= url_to('inventory-movement-show', $movement['original_movement_id']) ?>">Ver #<?= esc((string) $movement['original_movement_id']) ?></a></dd><?php endif ?></dl></div></div></div>
<div class="col-lg-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h6">Estado</h2><?php if ((int) $movement['is_reversed'] === 1): ?><div class="alert alert-warning mb-0">Este movimiento tiene una reversión compensatoria.</div><?php elseif ($movement['has_pending_valuation']): ?><div class="alert alert-warning mb-0">Existen cantidades pendientes de valoración.</div><?php else: ?><div class="alert alert-success mb-0">Movimiento confirmado.</div><?php endif ?></div></div></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Material</th><th class="text-end">Cantidad</th><th class="text-end">Stock anterior</th><th class="text-end">Stock posterior</th><?php if ($showCosts): ?><th class="text-end">Costo unitario</th><th class="text-end">Valor</th><?php endif ?><th>Valoración</th></tr></thead><tbody><?php foreach ($items as $item): ?><tr><td><span class="font-monospace"><?= esc($item['material_code']) ?></span> · <?= esc($item['material_name']) ?></td><td class="text-end"><?= $item['direction'] > 0 ? '+' : '-' ?><?= esc(number_format((float) $item['quantity'], 3, ',', '.')) ?> <?= esc($item['unit_symbol']) ?></td><td class="text-end"><?= esc(number_format((float) $item['stock_before'], 3, ',', '.')) ?></td><td class="text-end"><?= esc(number_format((float) $item['stock_after'], 3, ',', '.')) ?></td><?php if ($showCosts): ?><td class="text-end"><?= $item['unit_cost'] === null ? '—' : esc(number_format((float) $item['unit_cost'], 6, ',', '.')) ?></td><td class="text-end"><?= esc(number_format((float) $item['line_value'], 2, ',', '.')) ?></td><?php endif ?><td><?= $item['pending_valuation'] ? '<span class="badge text-bg-warning">Pendiente</span>' : '<span class="badge text-bg-success">Completa</span>' ?></td></tr><?php endforeach ?></tbody></table></div></div>
<?php if ($movement['type'] !== 'REVERSAL' && (int) $movement['is_reversed'] === 0 && auth()->user()?->can('inventory.reversals.request')): ?><div class="card border-warning"><div class="card-body"><h2 class="h5">Solicitar reversión</h2><p class="text-body-secondary">El movimiento original no cambiará. Otro administrador deberá aprobar el movimiento compensatorio.</p><form method="post" action="<?= url_to('inventory-reversal-request', $movement['id']) ?>"><?= csrf_field() ?><div class="input-group"><input class="form-control" name="reason" minlength="5" maxlength="2000" placeholder="Motivo obligatorio" required><button class="btn btn-outline-warning" type="submit">Solicitar</button></div></form></div></div><?php endif ?>
<?= $this->endSection() ?>
