<?= $this->extend('layouts/app') ?>
<?= $this->section('title') ?>Solicitar ajuste<?= $this->endSection() ?>
<?= $this->section('main') ?>
<div class="card border-0 shadow-sm mx-auto app-wide-form-card"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h4 mb-1">Solicitar ajuste</h1><p class="text-body-secondary mb-0">Usa cantidades positivas para aumentar y negativas para disminuir.</p></div><a class="btn btn-sm btn-outline-secondary" href="<?= url_to('inventory-requests') ?>">Volver</a></div>
<?= $this->include('partials/flash') ?>
<div class="alert alert-info">Otra persona administradora deberá aprobar la solicitud. El stock no cambiará hasta entonces.</div>
<form method="post" action="<?= url_to('inventory-adjustment-create') ?>" data-inventory-form><?= csrf_field() ?><div class="row g-3"><div class="col-md-5"><label class="form-label" for="warehouse_id">Bodega</label><select class="form-select" id="warehouse_id" name="warehouse_id" required><option value="">Selecciona...</option><?php foreach ($warehouses as $warehouse): ?><option value="<?= esc((string) $warehouse['id']) ?>" <?= (string) old('warehouse_id') === (string) $warehouse['id'] ? 'selected' : '' ?>><?= esc($warehouse['name']) ?></option><?php endforeach ?></select></div><div class="col-md-7"><label class="form-label" for="reason">Motivo y evidencia</label><textarea class="form-control" id="reason" name="reason" minlength="5" maxlength="2000" required><?= esc(old('reason')) ?></textarea></div></div>
<hr class="my-4"><div class="d-flex justify-content-between align-items-center"><h2 class="h5 mb-0">Variaciones solicitadas</h2><button class="btn btn-sm btn-outline-primary" type="button" data-add-inventory-row>Agregar material</button></div>
<div class="mt-3" data-inventory-items><div class="row g-2 align-items-end inventory-item-row mb-3"><div class="col-lg-4"><label class="form-label">Material</label><select class="form-select" name="material_id[]" required><option value="">Selecciona...</option><?php foreach ($materials as $material): ?><option value="<?= esc((string) $material['id']) ?>"><?= esc($material['code'] . ' - ' . $material['name'] . ' (' . $material['unit_symbol'] . ')') ?></option><?php endforeach ?></select></div><div class="col-lg-2"><label class="form-label">Variación</label><input class="form-control" type="number" name="quantity_delta[]" min="-99999999999.999" max="99999999999.999" step="0.001" placeholder="Ej. -2 o 5.5" required></div><div class="col-lg-2"><label class="form-label">Costo si aumenta</label><input class="form-control" type="number" name="unit_cost[]" min="0.000001" step="0.000001"></div><div class="col-lg-3"><label class="form-label">Motivo sin costo</label><input class="form-control" name="no_cost_reason[]" maxlength="500" placeholder="Si aumenta sin costo"></div><div class="col-lg-1"><button class="btn btn-outline-danger w-100" type="button" data-remove-inventory-row aria-label="Quitar material">×</button></div></div></div>
<button class="btn btn-primary" type="submit" <?= $materials === [] || $warehouses === [] ? 'disabled' : '' ?>>Enviar solicitud</button></form></div></div>
<?= $this->endSection() ?>
