<?= $this->extend('layouts/app') ?>
<?= $this->section('title') ?>Solicitudes de inventario<?= $this->endSection() ?>
<?= $this->section('main') ?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="h3 mb-1">Solicitudes de inventario</h1><p class="text-body-secondary mb-0">Ajustes y reversiones sujetos a segregación de funciones.</p></div><?php if (auth()->user()?->can('inventory.adjustments.request')): ?><a class="btn btn-primary" href="<?= url_to('inventory-adjustment-new') ?>">Solicitar ajuste</a><?php endif ?></div>
<?= $this->include('partials/flash') ?>
<form class="row g-2 mb-3" method="get"><div class="col-md-3"><select class="form-select" name="status"><option value="">Todos los estados</option><?php foreach (['PENDING'=>'Pendiente','REJECTED'=>'Rechazada','EXECUTED'=>'Ejecutada'] as $value => $label): ?><option value="<?= $value ?>" <?= $status === $value ? 'selected' : '' ?>><?= $label ?></option><?php endforeach ?></select></div><div class="col-auto"><button class="btn btn-outline-secondary">Filtrar</button></div></form>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Número</th><th>Fecha</th><th>Tipo</th><th>Bodega</th><th>Solicitante</th><th>Motivo</th><th>Estado</th><th>Decisión</th></tr></thead><tbody>
<?php foreach ($records as $record): ?><?php $canDecide = $record['type'] === 'REVERSAL' ? auth()->user()?->can('inventory.reversals.approve') : auth()->user()?->can('inventory.adjustments.approve'); ?><tr><td class="font-monospace"><?= esc($record['request_number']) ?></td><td><?= esc($record['requested_at']) ?></td><td><?= $record['type'] === 'ADJUSTMENT' ? 'Ajuste' : 'Reversión' ?></td><td><?= esc($record['warehouse_name']) ?></td><td><?= esc($record['requested_by_name']) ?></td><td><?= esc($record['reason']) ?></td><td><?= ['PENDING'=>'<span class="badge text-bg-warning">Pendiente</span>','REJECTED'=>'<span class="badge text-bg-danger">Rechazada</span>','EXECUTED'=>'<span class="badge text-bg-success">Ejecutada</span>'][$record['status']] ?></td><td><?php if ($record['status'] === 'PENDING' && $canDecide): ?><?php if ((int) $record['requested_by'] === (int) auth()->id()): ?><span class="small text-body-secondary">Debe decidir otra persona</span><?php else: ?><form method="post" action="<?= url_to('inventory-request-decide', $record['id']) ?>" class="d-flex flex-column gap-2"><?= csrf_field() ?><input class="form-control form-control-sm" name="comment" maxlength="1000" placeholder="Comentario; obligatorio al rechazar"><div class="btn-group btn-group-sm"><button class="btn btn-outline-success" name="decision" value="approve">Aprobar y ejecutar</button><button class="btn btn-outline-danger" name="decision" value="reject">Rechazar</button></div></form><?php endif ?><?php elseif ($record['executed_movement_id']): ?><a class="btn btn-sm btn-outline-primary" href="<?= url_to('inventory-movement-show', $record['executed_movement_id']) ?>">Ver movimiento</a><?php else: ?><?= esc($record['decision_comment'] ?? '—') ?><?php endif ?></td></tr><?php endforeach ?>
<?php if ($records === []): ?><tr><td colspan="8" class="text-center text-body-secondary py-4">No hay solicitudes.</td></tr><?php endif ?></tbody></table></div></div><div class="mt-3"><?= $pager->links() ?></div>
<?= $this->endSection() ?>
